version: "3"
services:
  redis-vector-db:
    image: redis/redis-stack:7.2.0-v9
    container_name: redis-vector-db
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - "d:/users/wxg/redis_data:/data" # Persist Redis data in the current directory
    environment:
      REDIS_ARGS: "--save 60 1 --appendonly yes"
